name: Health Check
on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to health check (default: latest)'
        required: false
        default: 'latest'
permissions:
  contents: read
  issues: write
jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Make health check script executable
        run: chmod +x health-check.sh
      - name: Run health check
        run: |
          IMAGE_TAG="${{ github.event.inputs.image_tag || 'latest' }}"
          ./health-check.sh "ghcr.io/${{ github.repository_owner }}/octoeverywhere:${IMAGE_TAG}"
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
      - name: Create issue on health check failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: "// Check if there's already an open health check issue\nconst issues = await github.rest.issues.listForRepo({\n  owner: context.repo.owner,\n  repo: context.repo.repo,\n  state: 'open',\n  labels: 'health-check,automated'\n});\n\nif (issues.data.length === 0) {\n  await github.rest.issues.create({\n    owner: context.repo.owner,\n    repo: context.repo.repo,\n    title: `Health Check Failed - ${new Date().toISOString().split('T')[0]}`,\n    body: `## Health Check Failure Alert\n    \n    **Date:** ${new Date().toISOString()}\n    **Workflow:** [${context.workflow}](${context.payload.repository.html_url}/actions/runs/${context.runId})\n    **Image:** ghcr.io/${{ github.repository_owner }}/octoeverywhere:${{ github.event.inputs.image_tag || 'latest' }}\n    \n    ## What Happened\n    The automated health check failed. This could indicate:\n    - Image is not available or corrupted\n    - Basic functionality is broken  \n    - Upstream configuration has changed significantly\n    - Container fails to start or crashes quickly\n    \n    ## Next Steps\n    1. Check the [workflow logs](${context.payload.repository.html_url}/actions/runs/${context.runId}) for details\n    2. Run the health check locally: \\`./health-check.sh\\`\n    3. If there's a real issue, consider using the [Emergency Rollback](${context.payload.repository.html_url}/actions/workflows/rollback.yml) workflow\n    4. Close this issue once the problem is resolved\n    \n    ## Manual Health Check\n    You can run a manual health check anytime:\n    - Go to Actions → Health Check → Run workflow\n    - Or run locally: \\`./health-check.sh [image-tag]\\`\n    `,\n    labels: ['health-check', 'automated', 'urgent']\n  });\n}\n"
